/*
 * Copyright (C) 2015 Guo Yunhe <guoyunhebrave@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package me.guoyunhe.fcm;

import javax.swing.DefaultComboBoxModel;
import org.xml.sax.SAXException;

/**
 *
 * @author Guo Yunhe <guoyunhebrave@gmail.com>
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabbedPanel = new javax.swing.JTabbedPane();
        fontTypePanel = new javax.swing.JScrollPane();
        fontTypeContentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sansComboBox = new javax.swing.JComboBox();
        serifComboBox = new javax.swing.JComboBox();
        monoComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        zhSansComboBox = new javax.swing.JComboBox();
        zhSerifComboBox = new javax.swing.JComboBox();
        zhMonoComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jaSansComboBox = new javax.swing.JComboBox();
        jaSerifComboBox = new javax.swing.JComboBox();
        jaMonoComboBox = new javax.swing.JComboBox();
        koSansComboBox = new javax.swing.JComboBox();
        koSerifComboBox = new javax.swing.JComboBox();
        koMonoComboBox = new javax.swing.JComboBox();
        fontHintPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        saveButtonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        tabbedPanel.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPanel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        fontTypeContentPanel.setOpaque(false);
        fontTypeContentPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sans Serif");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Serif");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Monospace");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Western fonts");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel7, gridBagConstraints);

        sansComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        sansComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nimbus Sans L", "文泉驿微米黑", "文泉驿正黑", "黑色" }));
        sansComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        sansComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sansComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(sansComboBox, gridBagConstraints);

        serifComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        serifComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        serifComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(serifComboBox, gridBagConstraints);

        monoComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        monoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        monoComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(monoComboBox, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Chinese fonts");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel3, gridBagConstraints);

        zhSansComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        zhSansComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nimbus Sans L", "文泉驿微米黑", "文泉驿正黑", "黑色" }));
        zhSansComboBox.setSelectedIndex(1);
        zhSansComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(zhSansComboBox, gridBagConstraints);

        zhSerifComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        zhSerifComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        zhSerifComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(zhSerifComboBox, gridBagConstraints);

        zhMonoComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        zhMonoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        zhMonoComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(zhMonoComboBox, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Japanese fonts");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Korean fonts");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jLabel4, gridBagConstraints);

        jaSansComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jaSansComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jaSansComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jaSansComboBox, gridBagConstraints);

        jaSerifComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jaSerifComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jaSerifComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jaSerifComboBox, gridBagConstraints);

        jaMonoComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jaMonoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jaMonoComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(jaMonoComboBox, gridBagConstraints);

        koSansComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        koSansComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        koSansComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(koSansComboBox, gridBagConstraints);

        koSerifComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        koSerifComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        koSerifComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(koSerifComboBox, gridBagConstraints);

        koMonoComboBox.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        koMonoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        koMonoComboBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        fontTypeContentPanel.add(koMonoComboBox, gridBagConstraints);

        fontTypePanel.setViewportView(fontTypeContentPanel);

        tabbedPanel.addTab("Font Family", fontTypePanel);

        javax.swing.GroupLayout fontHintPanelLayout = new javax.swing.GroupLayout(fontHintPanel);
        fontHintPanel.setLayout(fontHintPanelLayout);
        fontHintPanelLayout.setHorizontalGroup(
            fontHintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        fontHintPanelLayout.setVerticalGroup(
            fontHintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Font Hint", fontHintPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Subpixel Render", jPanel1);

        getContentPane().add(tabbedPanel);

        saveButtonPanel.setMaximumSize(new java.awt.Dimension(32767, 35));

        okButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        saveButtonPanel.add(okButton);

        cancelButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        saveButtonPanel.add(cancelButton);

        getContentPane().add(saveButtonPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    private void sansComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sansComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sansComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        MainWindow mw;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mw = new MainWindow();
                mw.setVisible(true);
                FontConfigXML fcxml = new FontConfigXML();

                FontList fontlist = new FontList();

                mw.refreshFontList(fontlist.getList());
            }
        });
        
        
    }
    
    public void refreshFontList(String[] list) {
        this.sansComboBox.setModel(new DefaultComboBoxModel(list));
        this.serifComboBox.setModel(new DefaultComboBoxModel(list));
        this.monoComboBox.setModel(new DefaultComboBoxModel(list));
        this.zhSansComboBox.setModel(new DefaultComboBoxModel(list));
        this.zhSerifComboBox.setModel(new DefaultComboBoxModel(list));
        this.zhMonoComboBox.setModel(new DefaultComboBoxModel(list));
        this.jaSansComboBox.setModel(new DefaultComboBoxModel(list));
        this.jaSerifComboBox.setModel(new DefaultComboBoxModel(list));
        this.jaMonoComboBox.setModel(new DefaultComboBoxModel(list));
        this.koSansComboBox.setModel(new DefaultComboBoxModel(list));
        this.koSerifComboBox.setModel(new DefaultComboBoxModel(list));
        this.koMonoComboBox.setModel(new DefaultComboBoxModel(list));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel fontHintPanel;
    private javax.swing.JPanel fontTypeContentPanel;
    private javax.swing.JScrollPane fontTypePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jaMonoComboBox;
    private javax.swing.JComboBox jaSansComboBox;
    private javax.swing.JComboBox jaSerifComboBox;
    private javax.swing.JComboBox koMonoComboBox;
    private javax.swing.JComboBox koSansComboBox;
    private javax.swing.JComboBox koSerifComboBox;
    private javax.swing.JComboBox monoComboBox;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox sansComboBox;
    private javax.swing.JPanel saveButtonPanel;
    private javax.swing.JComboBox serifComboBox;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JComboBox zhMonoComboBox;
    private javax.swing.JComboBox zhSansComboBox;
    private javax.swing.JComboBox zhSerifComboBox;
    // End of variables declaration//GEN-END:variables
}
